#Launch prompts workflow
name: PromptExecutor
'on':
  workflow_dispatch:
  push:
    paths:
      - fluidLLMTool/**
  pull_request:
    paths:
      - fluidLLMTool/**
jobs:
  prompt-test-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fluidLLMTool
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '22'
      - name: Deploy LLM Tool
        run: |
          yarn build-executor
        env:
          GITHUB_TOKEN: ${{ secrets.LLM_PROMPT_EXECUTOR_TOKEN }}
      - name: Ollama Installation and model pull
        run: |
          yarn ollama-run
      - name: Launch Prompt Tests
        run: |
          yarn install
          yarn test
